name: CI/CD
on:
  push:
    branches:
    - master
    paths:
    - "src/**.md"
    - "book.toml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: "./.github/acitons/build"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: "${{ secrets.ACTIONS_DEPLOY_KEY }}"
        EXTERNAL_REPOSITIORY: n-kats/test_mdbook_dist
        PUBLISH_BRANCH: main
        PUBLISH_DIR: ./book

